=== KingaJanicka/push2-groovebox/docs/schemas/v2/device.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pushpin.kinga.dev/schemas/v2/device.json",
    "title": "Device",
    "description": "A device in an instrument",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "slot": {
            "type": "integer"
        },
        "init": {
            "type": "array",
            "items": {
                "$ref": "/schemas/v2/message.json"
            }
        },
        "controls": {
            "type": "array",
            "items": {
                "$ref": "/schemas/v2/control.json"
            }
        }
    }
}

=== KingaJanicka/push2-groovebox/effect_definitions/combulator_2.json
{
	"name": "Combulator",
	"slot": 6,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/a/2/type",
			"value": 21
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "Center",
			"address": "/param/fx/a/2/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Offset 2",
			"address": "/param/fx/a/2/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Offset 3",
			"address": "/param/fx/a/2/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Feedback",
			"address": "/param/fx/a/2/param5",
			"min": 0,
			"max": 1,
			"bipolar": 1
		},
		{
			"$type": "control-range",
			"label": "Tone",
			"address": "/param/fx/a/2/param6",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-range",
			"label": "Mix",
			"address": "/param/fx/a/2/param12",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Input Noise",
			"address": "/param/fx/a/2/param1",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Pan 2",
			"address": "/param/fx/a/2/param10",
			"min": 0,
			"max": 1,
			"bipolar": 1
		},
		{
			"$type": "control-range",
			"label": "Pan 3",
			"address": "/param/fx/a/2/param11",
			"min": 0,
			"max": 1,
			"bipolar": 1
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-range",
			"label": "Comb 1 Mix",
			"address": "/param/fx/a/2/param7",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Comb 2 Mix",
			"address": "/param/fx/a/2/param8",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Comb 3 Mix",
			"address": "/param/fx/a/2/param9",
			"min": 0,
			"max": 1
		}
	]
}

=== KingaJanicka/push2-groovebox/device_definitions/string_1.json
{
	"name": "STRING",
	"slot": 0,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/a/mixer/osc1/mute",
			"value": 0
		},
		{
			"$type": "message",
			"$comment": "set osc type",
			"address": "/param/a/osc/1/type",
			"value": 9
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "PITCH",
			"address": "/param/a/osc/1/pitch",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-menu",
			"items": [
				{
					"$type": "menu-item",
					"label": "Burst Noise",
					"onselect": {
						"$type": "message",
						"$comment": "Burst Noise",
						"address": "/param/a/osc/1/param1",
						"value": 0
					}
				},
				{
					"$type": "menu-item",
					"label": "Burst Pink",
					"onselect": {
						"$type": "message",
						"$comment": "Burst Pink",
						"address": "/param/a/osc/1/param1",
						"value": 1
					}
				},
				{
					"$type": "menu-item",
					"label": "Burst Sine",
					"onselect": {
						"$type": "message",
						"$comment": "Burst Sine",
						"address": "/param/a/osc/1/param1",
						"value": 2
					}
				},
				{
					"$type": "menu-item",
					"label": "Burst Trian",
					"onselect": {
						"$type": "message",
						"$comment": "Burst Trian",
						"address": "/param/a/osc/1/param1",
						"value": 3
					}
				},
				{
					"$type": "menu-item",
					"label": "Burst Ramp",
					"onselect": {
						"$type": "message",
						"$comment": "Burst Ramp",
						"address": "/param/a/osc/1/param1",
						"value": 4
					}
				},
				{
					"$type": "menu-item",
					"label": "Burst Sq",
					"onselect": {
						"$type": "message",
						"$comment": "Burst Sq",
						"address": "/param/a/osc/1/param1",
						"value": 5
					}
				},
				{
					"$type": "menu-item",
					"label": "Burst Sweep",
					"onselect": {
						"$type": "message",
						"$comment": "Burst Sweep",
						"address": "/param/a/osc/1/param1",
						"value": 6
					}
				},
				{
					"$type": "menu-item",
					"label": "Noise",
					"onselect": {
						"$type": "message",
						"$comment": "Noise",
						"address": "/param/a/osc/1/param1",
						"value": 7
					}
				},
				{
					"$type": "menu-item",
					"label": "Pink",
					"onselect": {
						"$type": "message",
						"$comment": "Pink",
						"address": "/param/a/osc/1/param1",
						"value": 8
					}
				},
				{
					"$type": "menu-item",
					"label": "Sine",
					"onselect": {
						"$type": "message",
						"$comment": "Sine",
						"address": "/param/a/osc/1/param1",
						"value": 9
					}
				},
				{
					"$type": "menu-item",
					"label": "Triangle",
					"onselect": {
						"$type": "message",
						"$comment": "Triangle",
						"address": "/param/a/osc/1/param1",
						"value": 10
					}
				},
				{
					"$type": "menu-item",
					"label": "Ramp",
					"onselect": {
						"$type": "message",
						"$comment": "Ramp",
						"address": "/param/a/osc/1/param1",
						"value": 11
					}
				},
				{
					"$type": "menu-item",
					"label": "Square",
					"onselect": {
						"$type": "message",
						"$comment": "Square",
						"address": "/param/a/osc/1/param1",
						"value": 12
					}
				},
				{
					"$type": "menu-item",
					"label": "Sweep",
					"onselect": {
						"$type": "message",
						"$comment": "Sweep",
						"address": "/param/a/osc/1/param1",
						"value": 13
					}
				},
				{
					"$type": "menu-item",
					"label": "Audio in",
					"onselect": {
						"$type": "message",
						"$comment": "Audio in",
						"address": "/param/a/osc/1/param1",
						"value": 14
					}
				}
			]
		},
		{
			"$type": "control-range",
			"label": "EXCT. LVL",
			"address": "/param/a/osc/1/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "STR. 1 DECAY",
			"address": "/param/a/osc/1/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "STR. 2 DECAY",
			"address": "/param/a/osc/1/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "STR. 2 DETUNE",
			"address": "/param/a/osc/1/param5",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "STR. BAL.",
			"address": "/param/a/osc/1/param6",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "STIFFNESS",
			"address": "/param/a/osc/1/param7",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-range",
			"label": "KEYTRACK",
			"address": "/param/a/osc/1/keytrack",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "RETRIG",
			"address": "/param/a/osc/1/retrigger",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "FIL ROUTE",
			"address": "/param/a/mixer/osc1/route",
			"min": 0,
			"max": 2
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-range",
			"label": "FM DEPTH",
			"address": "/param/a/osc/fm_depth",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "FM ROUTING",
			"address": "/param/a/osc/fm_routing",
			"min": 0,
			"max": 3
		}
	]
}

=== KingaJanicka/push2-groovebox/effect_definitions/freq_shifter_global.json
{
	"name": "Freq. Shift",
	"slot": 7,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/global/1/type",
			"value": 7
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "Left Shift",
			"address": "/param/fx/global/1/param1",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Right Shift",
			"address": "/param/fx/global/1/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Delay Time",
			"address": "/param/fx/global/1/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Delay Fdbk.",
			"address": "/param/fx/global/1/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Mix",
			"address": "/param/fx/global/1/param2",
			"min": 0,
			"max": 1
		}
	]
}

=== KingaJanicka/push2-groovebox/device_definitions/none_6.json
{
	"name": "No FX",
	"slot": 6,
	"init": [
		{
			"$type": "message",
			"$comment": "set fx type",
			"address": "/param/fx/a/2/type",
			"value": 0
		}
	],
	"controls": [
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		}
	]
}

=== KingaJanicka/push2-groovebox/device_definitions/hhh/fm2_2.json
{
	"name": "FM2",
	"slot": 1,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/a/mixer/osc2/mute",
			"value": 0
		},
		{
			"$type": "message",
			"$comment": "set osc type",
			"address": "/param/a/osc/2/type",
			"value": 6
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "PITCH",
			"address": "/param/a/osc/2/pitch",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "M1 AMOUNT",
			"address": "/param/a/osc/2/param1",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "M1 RATIO",
			"address": "/param/a/osc/2/param2",
			"min": 0,
			"max": 32
		},
		{
			"$type": "control-range",
			"label": "M2 AMOUNT",
			"address": "/param/a/osc/2/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "M2 RATIO",
			"address": "/param/a/osc/2/param4",
			"min": 0,
			"max": 32
		},
		{
			"$type": "control-range",
			"label": "M1/2 OFFSET",
			"address": "/param/a/osc/2/param5",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "M1/2 PHASE",
			"address": "/param/a/osc/2/param6",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "FEEDBACK",
			"address": "/param/a/osc/2/param7",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-range",
			"label": "KEYTRACK",
			"address": "/param/a/osc/2/keytrack",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "RETRIG",
			"address": "/param/a/osc/2/retrigger",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "FIL ROUTE",
			"address": "/param/a/mixer/osc2/route",
			"min": 0,
			"max": 2
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-range",
			"label": "FM DEPTH",
			"address": "/param/a/osc/fm_depth",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "FM ROUTING",
			"address": "/param/a/osc/fm_routing",
			"min": 0,
			"max": 3
		}
	]
}

=== KingaJanicka/push2-groovebox/effect_definitions/eq11_global.json
{
	"name": "EQ 11",
	"slot": 7,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/global/1/type",
			"value": 16
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "30hz",
			"address": "/param/fx/global/1/param1",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "120hz",
			"address": "/param/fx/global/1/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "500hz",
			"address": "/param/fx/global/1/param5",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "2khz",
			"address": "/param/fx/global/1/param7",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "8khz",
			"address": "/param/fx/global/1/param9",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "16khz",
			"address": "/param/fx/global/1/param11",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-range",
			"label": "60hz",
			"address": "/param/fx/global/1/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "250hz",
			"address": "/param/fx/global/1/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "1khz",
			"address": "/param/fx/global/1/param6",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "4khz",
			"address": "/param/fx/global/1/param8",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "12khz",
			"address": "/param/fx/global/1/param10",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-range",
			"label": "Gain",
			"address": "/param/fx/global/1/param12",
			"min": 0,
			"max": 1
		}
	]
}

=== KingaJanicka/push2-groovebox/definitions/effect_definitions/spring_global.json
{
	"name": "Spring",
	"slot": 7,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/global/1/type",
			"value": 27
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "Size",
			"address": "/param/fx/global/1/param1",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Decay",
			"address": "/param/fx/global/1/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Reflections",
			"address": "/param/fx/global/1/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "HF Damp",
			"address": "/param/fx/global/1/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Spin",
			"address": "/param/fx/global/1/param5",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Chaos",
			"address": "/param/fx/global/1/param6",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-menu",
			"items": [
				{
					"$type": "menu-item",
					"label": "Leave be",
					"onselect": {
						"$type": "message",
						"$comment": "1",
						"address": "/param/fx/global/1/param7",
						"value": 0
					}
				},
				{
					"$type": "menu-item",
					"label": "KNOCK",
					"onselect": {
						"$type": "message",
						"$comment": "2",
						"address": "/param/fx/global/1/param7",
						"value": 1
					}
				}
			]
		},
		{
			"$type": "control-range",
			"label": "Mix",
			"address": "/param/fx/global/1/param8",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/global/1/param9"
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/global/1/param10"
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/global/1/param11"
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/global/1/param12"
		}
	]
}

=== KingaJanicka/push2-groovebox/effect_definitions/treemonster_1.json
{
	"name": "Treemonster",
	"slot": 5,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/a/1/type",
			"value": 24
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "Pitch Thresh.",
			"address": "/param/fx/a/1/param1",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Pitch Speed",
			"address": "/param/fx/a/1/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Pitch Low Cut",
			"address": "/param/fx/a/1/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Pitch High Cut",
			"address": "/param/fx/a/1/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Osc Pitch",
			"address": "/param/fx/a/1/param5",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Osc Ring Mod",
			"address": "/param/fx/a/1/param6",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Width",
			"address": "/param/fx/a/1/param7",
			"min": 0,
			"max": 1,
			"bipolar": 1
		},
		{
			"$type": "control-range",
			"label": "Mix",
			"address": "/param/fx/a/1/param8",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/a/1/param9"
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/a/1/param10"
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/a/1/param11"
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/a/1/param12"
		}
	]
}
