=== KingaJanicka/push2-groovebox/docs/schemas/v2/device.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pushpin.kinga.dev/schemas/v2/device.json",
    "title": "Device",
    "description": "A device in an instrument",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "slot": {
            "type": "integer"
        },
        "init": {
            "type": "array",
            "items": {
                "$ref": "/schemas/v2/message.json"
            }
        },
        "controls": {
            "type": "array",
            "items": {
                "$ref": "/schemas/v2/control.json"
            }
        }
    }
}

=== KingaJanicka/push2-groovebox/effect_definitions/freq_shifter.json
{
	"name": "Freq. Shift",
	"slot": 0,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/a/1/type",
			"value": 7
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "Left Shift",
			"address": "/param/fx/a/1/param1",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Right Shift",
			"address": "/param/fx/a/1/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Delay Time",
			"address": "/param/fx/a/1/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Delay Fdbk.",
			"address": "/param/fx/a/1/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Mix",
			"address": "/param/fx/a/1/param2",
			"min": 0,
			"max": 1
		}
	]
}

=== KingaJanicka/push2-groovebox/effect_definitions/treemonster_global.json
{
	"name": "Treemonster",
	"slot": 7,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/global/1/type",
			"value": 24
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "Pitch Thresh.",
			"address": "/param/fx/global/1/param1",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Pitch Speed",
			"address": "/param/fx/global/1/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Pitch Low Cut",
			"address": "/param/fx/global/1/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Pitch High Cut",
			"address": "/param/fx/global/1/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Osc Pitch",
			"address": "/param/fx/global/1/param5",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Osc Ring Mod",
			"address": "/param/fx/global/1/param6",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Width",
			"address": "/param/fx/global/1/param7",
			"min": 0,
			"max": 1,
			"bipolar": 1
		},
		{
			"$type": "control-range",
			"label": "Mix",
			"address": "/param/fx/global/1/param8",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/global/1/param9"
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/global/1/param10"
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/global/1/param11"
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/global/1/param12"
		}
	]
}

=== KingaJanicka/push2-groovebox/definitions/effect_definitions/delay_global.json
{
	"name": "Delay",
	"slot": 7,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/global/1/type",
			"value": 1
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "Input Channel",
			"address": "/param/fx/global/1/param9",
			"min": 0,
			"max": 1,
			"bipolar": 1
		},
		{
			"$type": "control-range",
			"label": "Time L",
			"address": "/param/fx/global/1/param1",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Time R",
			"address": "/param/fx/global/1/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Feedback",
			"address": "/param/fx/global/1/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Fdbk X-Feed",
			"address": "/param/fx/global/1/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Fdbk Low Cut",
			"address": "/param/fx/global/1/param5",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Fdbk High Cut",
			"address": "/param/fx/global/1/param6",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Mix",
			"address": "/param/fx/global/1/param11",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Mod Rate",
			"address": "/param/fx/global/1/param7",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Mod Depth",
			"address": "/param/fx/global/1/param8",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/global/1/param12"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-range",
			"label": "Width",
			"address": "/param/fx/global/1/param12",
			"min": 0,
			"max": 1,
			"bipolar": 1
		}
	]
}

=== KingaJanicka/push2-groovebox/effect_definitions/bonsai_2.json
{
	"name": "Bonsai",
	"slot": 6,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/a/2/type",
			"value": 28
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "Gain in",
			"address": "/param/fx/a/2/param1",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Amount",
			"address": "/param/fx/a/2/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Distort",
			"address": "/param/fx/a/2/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-menu",
			"items": [
				{
					"$type": "menu-item",
					"label": "Tilt Fil.",
					"onselect": {
						"$type": "message",
						"$comment": "1",
						"address": "/param/a/osc/1/param4",
						"value": 0
					}
				},
				{
					"$type": "menu-item",
					"label": "Pull Mids",
					"onselect": {
						"$type": "message",
						"$comment": "2",
						"address": "/param/a/osc/1/param4",
						"value": 1
					}
				}
			]
		},
		{
			"$type": "control-menu",
			"items": [
				{
					"$type": "menu-item",
					"label": "Gentle",
					"onselect": {
						"$type": "message",
						"$comment": "1",
						"address": "/param/a/osc/1/param4",
						"value": 0
					}
				},
				{
					"$type": "menu-item",
					"label": "Normal",
					"onselect": {
						"$type": "message",
						"$comment": "2",
						"address": "/param/a/osc/1/param4",
						"value": 1
					}
				},
				{
					"$type": "menu-item",
					"label": "Hard",
					"onselect": {
						"$type": "message",
						"$comment": "3",
						"address": "/param/a/osc/1/param10",
						"value": 2
					}
				},
				{
					"$type": "menu-item",
					"label": "Harsh",
					"onselect": {
						"$type": "message",
						"$comment": "4",
						"address": "/param/a/osc/1/param10",
						"value": 3
					}
				}
			]
		},
		{
			"$type": "control-range",
			"label": "Amount",
			"address": "/param/fx/a/2/param6",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Noise Sens",
			"address": "/param/fx/a/2/param7",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Noise Gain",
			"address": "/param/fx/a/2/param8",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Dull",
			"address": "/param/fx/a/2/param9",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Gain Out",
			"address": "/param/fx/a/2/param10",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Mix",
			"address": "/param/fx/a/2/param11",
			"min": 0,
			"max": 1
		}
	]
}

=== KingaJanicka/push2-groovebox/effect_definitions/reverb2_1.json
{
	"name": "Reverb 2",
	"slot": 5,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/a/1/type",
			"value": 1
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "Pre-Delay",
			"address": "/param/fx/a/1/param1",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-switch",
			"label": "Band",
			"groups": [
				{
					"$type": "group",
					"label": "Reverb",
					"controls": [
						{
							"$type": "control-range",
							"label": "Room Size",
							"address": "/param/fx/a/1/param2",
							"min": 0,
							"max": 1
						},
						{
							"$type": "control-range",
							"label": "Decay Time",
							"address": "/param/fx/a/1/param3",
							"min": 0,
							"max": 1
						},
						{
							"$type": "control-range",
							"label": "Diffusion",
							"address": "/param/fx/a/1/param4",
							"min": 0,
							"max": 1
						},
						{
							"$type": "control-range",
							"label": "Buildup",
							"address": "/param/fx/a/1/param5",
							"min": 0,
							"max": 1
						},
						{
							"$type": "control-range",
							"label": "Modulation",
							"address": "/param/fx/a/1/param6",
							"min": 0,
							"max": 1
						}
					]
				},
				{
					"$type": "group",
					"label": "EQ",
					"controls": [
						{
							"$type": "control-range",
							"label": "Low Damp",
							"address": "/param/fx/a/1/param7",
							"min": 0,
							"max": 1
						},
						{
							"$type": "control-range",
							"label": "High Damp",
							"address": "/param/fx/a/1/param8",
							"min": 0,
							"max": 1
						}
					]
				}
			]
		},
		{
			"$type": "control-range",
			"label": "Mix",
			"address": "/param/fx/a/1/param10",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Width",
			"address": "/param/fx/a/1/param9",
			"min": 0,
			"max": 1
		}
	]
}

=== KingaJanicka/push2-groovebox/definitions/modulation_definitions/macros.json
{
    "name": "Macros",
    "slot": 14,
    "init": [],
    "controls": [
        {
            "$type": "control-range",
            "label": "Macro 1",
            "address": "/param/macro/1",
            "min": 0,
            "max": 1
        },
        {
            "$type": "control-range",
            "label": "Macro 2",
            "address": "/param/macro/2",
            "min": 0,
            "max": 1
        },
        {
            "$type": "control-range",
            "label": "Macro 3",
            "address": "/param/macro/3",
            "min": 0,
            "max": 1
        },
        {
            "$type": "control-range",
            "label": "Macro 4",
            "address": "/param/macro/4",
            "min": 0,
            "max": 1
        },
        {
            "$type": "control-range",
            "label": "Macro 5",
            "address": "/param/macro/5",
            "min": 0,
            "max": 1
        },
        {
            "$type": "control-range",
            "label": "Macro 6",
            "address": "/param/macro/6",
            "min": 0,
            "max": 1
        },
        {
            "$type": "control-range",
            "label": "Macro 7",
            "address": "/param/macro/7",
            "min": 0,
            "max": 1
        },
        {
            "$type": "control-range",
            "label": "Macro 8",
            "address": "/param/macro/8",
            "min": 0,
            "max": 1
        }
    ]
}

=== KingaJanicka/push2-groovebox/effect_definitions/spring_2.json
{
	"name": "Spring",
	"slot": 6,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/a/2/type",
			"value": 27
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "Size",
			"address": "/param/fx/a/2/param1",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Decay",
			"address": "/param/fx/a/2/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Reflections",
			"address": "/param/fx/a/2/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "HF Damp",
			"address": "/param/fx/a/2/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Spin",
			"address": "/param/fx/a/2/param5",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Chaos",
			"address": "/param/fx/a/2/param6",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Knock",
			"address": "/param/fx/a/2/param7",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Mix",
			"address": "/param/fx/a/2/param8",
			"min": 0,
			"max": 1
		}
	]
}

=== KingaJanicka/push2-groovebox/device_definitions/hhh/alias_2.json
{
	"name": "ALIAS",
	"slot": 1,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/a/mixer/osc2/mute",
			"value": 0
		},
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/a/osc/2/type",
			"value": 11
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "PITCH",
			"address": "/param/a/osc/2/pitch",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-menu",
			"items": [
				{
					"$type": "menu-item",
					"label": "Sine",
					"onselect": {
						"$type": "message",
						"$comment": "Sine",
						"address": "/param/a/osc/2/param1",
						"value": 0
					}
				},
				{
					"$type": "menu-item",
					"label": "Ramp",
					"onselect": {
						"$type": "message",
						"$comment": "Ramp",
						"address": "/param/a/osc/2/param1",
						"value": 1
					}
				},
				{
					"$type": "menu-item",
					"label": "Pulse",
					"onselect": {
						"$type": "message",
						"$comment": "Pulse",
						"address": "/param/a/osc/2/param1",
						"value": 2
					}
				},
				{
					"$type": "menu-item",
					"label": "Noise",
					"onselect": {
						"$type": "message",
						"$comment": "Noise",
						"address": "/param/a/osc/2/param1",
						"value": 3
					}
				},
				{
					"$type": "menu-item",
					"label": "Addative",
					"onselect": {
						"$type": "message",
						"$comment": "Addative",
						"address": "/param/a/osc/2/param1",
						"value": 17
					}
				},
				{
					"$type": "menu-item",
					"label": "TX2",
					"onselect": {
						"$type": "message",
						"$comment": "TX2",
						"address": "/param/a/osc/2/param1",
						"value": 10
					}
				},
				{
					"$type": "menu-item",
					"label": "TX3",
					"onselect": {
						"$type": "message",
						"$comment": "TX3",
						"address": "/param/a/osc/2/param1",
						"value": 11
					}
				},
				{
					"$type": "menu-item",
					"label": "TX4",
					"onselect": {
						"$type": "message",
						"$comment": "TX4",
						"address": "/param/a/osc/2/param1",
						"value": 12
					}
				},
				{
					"$type": "menu-item",
					"label": "TX5",
					"onselect": {
						"$type": "message",
						"$comment": "TX5",
						"address": "/param/a/osc/2/param1",
						"value": 13
					}
				},
				{
					"$type": "menu-item",
					"label": "TX6",
					"onselect": {
						"$type": "message",
						"$comment": "TX6",
						"address": "/param/a/osc/2/param1",
						"value": 14
					}
				},
				{
					"$type": "menu-item",
					"label": "TX7",
					"onselect": {
						"$type": "message",
						"$comment": "TX7",
						"address": "/param/a/osc/2/param1",
						"value": 15
					}
				},
				{
					"$type": "menu-item",
					"label": "TX8",
					"onselect": {
						"$type": "message",
						"$comment": "TX8",
						"address": "/param/a/osc/2/param1",
						"value": 16
					}
				},
				{
					"$type": "menu-item",
					"label": "Mem Alias",
					"onselect": {
						"$type": "message",
						"$comment": "Mem Alias",
						"address": "/param/a/osc/2/param1",
						"value": 4
					}
				},
				{
					"$type": "menu-item",
					"label": "Mem Osc",
					"onselect": {
						"$type": "message",
						"$comment": "Mem Osc",
						"address": "/param/a/osc/2/param1",
						"value": 5
					}
				},
				{
					"$type": "menu-item",
					"label": "Mem Arp",
					"onselect": {
						"$type": "message",
						"$comment": "Mem Arp",
						"address": "/param/a/osc/2/param1",
						"value": 8
					}
				},
				{
					"$type": "menu-item",
					"label": "Mem Scene",
					"onselect": {
						"$type": "message",
						"$comment": "Mem Scene",
						"address": "/param/a/osc/2/param1",
						"value": 6
					}
				},
				{
					"$type": "menu-item",
					"label": "Mem Daw",
					"onselect": {
						"$type": "message",
						"$comment": "Mem Daw",
						"address": "/param/a/osc/2/param1",
						"value": 7
					}
				},
				{
					"$type": "menu-item",
					"label": "Audio in",
					"onselect": {
						"$type": "message",
						"$comment": "Audio in",
						"address": "/param/a/osc/2/param1",
						"value": 9
					}
				}
			]
		},
		{
			"$type": "control-range",
			"label": "WARP",
			"address": "/param/a/osc/2/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "MASK",
			"address": "/param/a/osc/2/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "THRESHOLD",
			"address": "/param/a/osc/2/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "BITCRUSH",
			"address": "/param/a/osc/2/param5",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "UNI. DET",
			"address": "/param/a/osc/2/param6",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "UNI. VOICES",
			"address": "/param/a/osc/2/param7",
			"min": 0,
			"max": 16
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-range",
			"label": "KEYTRACK",
			"address": "/param/a/osc/2/keytrack",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "RETRIG",
			"address": "/param/a/osc/2/retrigger",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "FIL ROUTE",
			"address": "/param/a/mixer/osc2/route",
			"min": 0,
			"max": 2
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-range",
			"label": "FM DEPTH",
			"address": "/param/a/osc/fm_depth",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "FM ROUTING",
			"address": "/param/a/osc/fm_routing",
			"min": 0,
			"max": 3
		}
	]
}
