=== KingaJanicka/push2-groovebox/docs/schemas/v2/device.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://pushpin.kinga.dev/schemas/v2/device.json",
    "title": "Device",
    "description": "A device in an instrument",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "slot": {
            "type": "integer"
        },
        "init": {
            "type": "array",
            "items": {
                "$ref": "/schemas/v2/message.json"
            }
        },
        "controls": {
            "type": "array",
            "items": {
                "$ref": "/schemas/v2/control.json"
            }
        }
    }
}

=== KingaJanicka/push2-groovebox/device_definitions/none_7.json
{
	"name": "No FX",
	"slot": 7,
	"init": [
		{
			"$type": "message",
			"$comment": "set fx type",
			"address": "/param/fx/global/1/type",
			"value": 0
		}
	],
	"controls": [
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		}
	]
}

=== KingaJanicka/push2-groovebox/effect_definitions/conditioner.json
{
	"name": "Conditioner",
	"slot": 0,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/a/1/type",
			"value": 8
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "Bass",
			"address": "/param/fx/a/1/param1",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Treble",
			"address": "/param/fx/a/1/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "St. Width",
			"address": "/param/fx/a/1/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "St. Balance",
			"address": "/param/fx/a/1/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Threshold",
			"address": "/param/fx/a/1/param5",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Attack",
			"address": "/param/fx/a/1/param6",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Release",
			"address": "/param/fx/a/1/param7",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Gain",
			"address": "/param/fx/a/1/param8",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Side Low Cut",
			"address": "/param/fx/a/1/param9",
			"min": 0,
			"max": 1
		}
	]
}

=== KingaJanicka/push2-groovebox/effect_definitions/exciter_1.json
{
	"name": "Exciter",
	"slot": 5,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/a/1/type",
			"value": 19
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "Drive",
			"address": "/param/fx/a/1/param1",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Tone",
			"address": "/param/fx/a/1/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Attack",
			"address": "/param/fx/a/1/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Release",
			"address": "/param/fx/a/1/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Mix",
			"address": "/param/fx/a/1/param5",
			"min": 0,
			"max": 1
		}
	]
}

=== KingaJanicka/push2-groovebox/definitions/effect_definitions/exciter_global.json
{
	"name": "Exciter",
	"slot": 7,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/global/1/type",
			"value": 19
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "Exciter Drive",
			"address": "/param/fx/global/1/param1",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Exciter Tone",
			"address": "/param/fx/global/1/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Shape Attack",
			"address": "/param/fx/global/1/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Shape Release",
			"address": "/param/fx/global/1/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-range",
			"label": "Mix",
			"address": "/param/fx/global/1/param5",
			"min": 0,
			"max": 1
		}
	]
}

=== KingaJanicka/push2-groovebox/effect_definitions/resonator_1.json
{
	"name": "Resonator",
	"slot": 5,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/a/1/type",
			"value": 17
		}
	],
	"controls": [
		{
			"$type": "control-switch",
			"label": "Band",
			"groups": [
				{
					"$type": "group",
					"label": "Band 1",
					"controls": [
						{
							"$type": "control-range",
							"label": "Freq 1",
							"address": "/param/fx/a/1/param1",
							"min": 0,
							"max": 1
						},
						{
							"$type": "control-range",
							"label": "Res 1",
							"address": "/param/fx/a/1/param2",
							"min": 0,
							"max": 1
						},
						{
							"$type": "control-range",
							"label": "Gain 1",
							"address": "/param/fx/a/1/param3",
							"min": 0,
							"max": 1
						}
					]
				},
				{
					"$type": "group",
					"label": "Band 2",
					"controls": [
						{
							"$type": "control-range",
							"label": "Freq 2",
							"address": "/param/fx/a/1/param4",
							"min": 0,
							"max": 1
						},
						{
							"$type": "control-range",
							"label": "Res 2",
							"address": "/param/fx/a/1/param5",
							"min": 0,
							"max": 1
						},
						{
							"$type": "control-range",
							"label": "Gain 2",
							"address": "/param/fx/a/1/param6",
							"min": 0,
							"max": 1
						}
					]
				},
				{
					"$type": "group",
					"label": "Band 3",
					"controls": [
						{
							"$type": "control-range",
							"label": "Freq 3",
							"address": "/param/fx/a/1/param7",
							"min": 0,
							"max": 1
						},
						{
							"$type": "control-range",
							"label": "Res 3",
							"address": "/param/fx/a/1/param8",
							"min": 0,
							"max": 1
						},
						{
							"$type": "control-range",
							"label": "Gain 3",
							"address": "/param/fx/a/1/param9",
							"min": 0,
							"max": 1
						}
					]
				}
			]
		},
		{
			"$type": "control-menu",
			"items": [
				{
					"$type": "menu-item",
					"label": "Lowpass",
					"onselect": {
						"$type": "message",
						"$comment": "1",
						"address": "/param/a/osc/1/param10",
						"value": 0
					}
				},
				{
					"$type": "menu-item",
					"label": "Bandpass",
					"onselect": {
						"$type": "message",
						"$comment": "2",
						"address": "/param/a/osc/1/param10",
						"value": 1
					}
				},
				{
					"$type": "menu-item",
					"label": "BP+Notch",
					"onselect": {
						"$type": "message",
						"$comment": "3",
						"address": "/param/a/osc/1/param10",
						"value": 2
					}
				},
				{
					"$type": "menu-item",
					"label": "Highpass",
					"onselect": {
						"$type": "message",
						"$comment": "4",
						"address": "/param/a/osc/1/param10",
						"value": 3
					}
				}
			]
		},
		{
			"$type": "control-range",
			"label": "Gain Out",
			"address": "/param/fx/a/1/param11",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Mix",
			"address": "/param/fx/a/1/param12",
			"min": 0,
			"max": 1
		}
	]
}

=== KingaJanicka/push2-groovebox/definitions/effect_definitions/freq_shifter_global.json
{
	"name": "Freq. Shifter",
	"slot": 7,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/global/1/type",
			"value": 7
		},
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/global/1/param1/extend+",
			"value": 7
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "Left Shift",
			"address": "/param/fx/global/1/param1",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Right Shift",
			"address": "/param/fx/global/1/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Delay Time",
			"address": "/param/fx/global/1/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Delay Fdbk.",
			"address": "/param/fx/global/1/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-range",
			"label": "Mix",
			"address": "/param/fx/global/1/param5",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/global/1/param6"
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/global/1/param7"
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/global/1/param8"
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/global/1/param9"
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/global/1/param10"
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/global/1/param11"
		},
		{
			"$type": "control-spacer-address",
			"address": "/param/fx/global/1/param12"
		}
	]
}

=== KingaJanicka/push2-groovebox/effect_definitions/phaser_2.json
{
	"name": "Phaser",
	"slot": 6,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/fx/a/2/type",
			"value": 3
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "Stage Count",
			"address": "/param/fx/a/2/param9",
			"min": 0,
			"max": 16
		},
		{
			"$type": "control-range",
			"label": "Stage Spread",
			"address": "/param/fx/a/2/param10",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Stage Center",
			"address": "/param/fx/a/2/param1",
			"min": 0,
			"max": 1,
			"bipolar": 1
		},
		{
			"$type": "control-range",
			"label": "Stage Sharp",
			"address": "/param/fx/a/2/param3",
			"min": 0,
			"max": 1,
			"bipolar": 1
		},
		{
			"$type": "control-range",
			"label": "Stage Fdbk",
			"address": "/param/fx/a/2/param2",
			"min": 0,
			"max": 1,
			"bipolar": 1
		},
		{
			"$type": "control-range",
			"label": "Tone",
			"address": "/param/fx/a/2/param12",
			"min": 0,
			"max": 1,
			"bipolar": 1
		},
		{
			"$type": "control-range",
			"label": "Width",
			"address": "/param/fx/a/2/param8",
			"min": 0,
			"max": 1,
			"bipolar": 1
		},
		{
			"$type": "control-range",
			"label": "Mix",
			"address": "/param/fx/a/2/param7",
			"min": 0,
			"max": 1,
			"bipolar": 1
		},
		{
			"$type": "control-menu",
			"items": [
				{
					"$type": "menu-item",
					"label": "Sine",
					"onselect": {
						"$type": "message",
						"$comment": "1",
						"address": "/param/fx/a/2/param11",
						"value": 0
					}
				},
				{
					"$type": "menu-item",
					"label": "Triangle",
					"onselect": {
						"$type": "message",
						"$comment": "2",
						"address": "/param/fx/a/2/param11",
						"value": 1
					}
				},
				{
					"$type": "menu-item",
					"label": "Sawtooth",
					"onselect": {
						"$type": "message",
						"$comment": "3",
						"address": "/param/fx/a/2/param11",
						"value": 2
					}
				},
				{
					"$type": "menu-item",
					"label": "Noise",
					"onselect": {
						"$type": "message",
						"$comment": "4",
						"address": "/param/fx/a/2/param11",
						"value": 3
					}
				},
				{
					"$type": "menu-item",
					"label": "S&H",
					"onselect": {
						"$type": "message",
						"$comment": "5",
						"address": "/param/fx/a/2/param11",
						"value": 4
					}
				},
				{
					"$type": "menu-item",
					"label": "Square",
					"onselect": {
						"$type": "message",
						"$comment": "6",
						"address": "/param/fx/a/2/param11",
						"value": 5
					}
				}
			]
		},
		{
			"$type": "control-range",
			"label": "Mod Rate",
			"address": "/param/fx/a/2/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Mod Depth",
			"address": "/param/fx/a/2/param5",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Mod Stereo",
			"address": "/param/fx/a/2/param6",
			"min": 0,
			"max": 1
		}
	]
}

=== KingaJanicka/push2-groovebox/device_definitions/classic_2.json
{
	"name": "CLASSIC 2",
	"slot": 1,
	"init": [
		{
			"$type": "message",
			"$comment": "unmute osc",
			"address": "/param/a/mixer/osc2/mute",
			"value": 0
		},
		{
			"$type": "message",
			"$comment": "set osc type",
			"address": "/param/a/osc/2/type",
			"value": 0
		}
	],
	"controls": [
		{
			"$type": "control-range",
			"label": "Pitch",
			"address": "/param/a/osc/2/pitch",
			"min": 0,
			"max": 1,
			"bipolar": 1
		},
		{
			"$type": "control-range",
			"label": "Shape",
			"address": "/param/a/osc/2/param1",
			"min": 0,
			"max": 1,
			"bipolar": 1
		},
		{
			"$type": "control-range",
			"label": "Width 1",
			"address": "/param/a/osc/2/param2",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Width 2",
			"address": "/param/a/osc/2/param3",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Sub Mix",
			"address": "/param/a/osc/2/param4",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Osc Sync",
			"address": "/param/a/osc/2/param5",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Unison Detune",
			"address": "/param/a/osc/2/param6",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Unison Voices",
			"address": "/param/a/osc/2/param7",
			"min": 0,
			"max": 16
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-spacer"
		},
		{
			"$type": "control-range",
			"label": "Keytrack",
			"address": "/param/a/osc/2/keytrack",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Retrig",
			"address": "/param/a/osc/2/retrigger",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "Filter Routing",
			"address": "/param/a/mixer/osc2/route",
			"min": 0,
			"max": 2
		},
		{
			"$type": "control-range",
			"label": "FM Depth",
			"address": "/param/a/osc/fm_depth",
			"min": 0,
			"max": 1
		},
		{
			"$type": "control-range",
			"label": "FM Routing",
			"address": "/param/a/osc/fm_routing",
			"min": 0,
			"max": 3
		}
	]
}
