=== KingaJanicka/push2-groovebox/docs/schemas/v1.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://pushpin.kinga.dev/schemas/v1.json",
    "$ref": "#/definitions/Device",
    "definitions": {
        "Device": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "device_name": {
                    "type": "string"
                },
                "device_slots": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "minItems": 1,
                        "maxItems": 8
                    }
                },
                "init": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OscMessage"
                    }
                },
                "osc": {
                    "$ref": "#/definitions/Osc"
                }
            },
            "required": [
                "device_name",
                "device_slots",
                "init",
                "osc"
            ],
            "title": "Device"
        },
        "Spacer": {
            "type": "array",
            "maxItems": 0
        },
        "Parameter": {
            "type": "array",
            "title": "Parameter",
            "minItems": 4,
            "maxItems": 4,
            "items": [
                {
                    "name": "label",
                    "type": "string"
                },
                {
                    "name": "address",
                    "type": "string"
                },
                {
                    "name": "min",
                    "default": 0.0,
                    "type": "number"
                },
                {
                    "name": "max",
                    "default": 1.0,
                    "type": "number"
                }
            ]
        },
        "MacroParameter": {
            "type": "array",
            "title": "MacroParameter",
            "minItems": 2,
            "maxItems": 2,
            "items": [
                {
                    "type": "string"
                },
                {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": [
                            {
                                "name": "address",
                                "type": "string"
                            },
                            {
                                "name": "min",
                                "type": "number"
                            },
                            {
                                "name": "max",
                                "type": "number"
                            }
                        ]
                    }
                }
            ]
        },
        "Osc": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "section": {
                    "type": "string"
                },
                "controls": {
                    "type": "array",
                    "contains": {
                        "anyOf": [
                            {
                                "$ref": "#/definitions/Parameter"
                            },
                            {
                                "$ref": "#/definitions/MacroParameter"
                            },
                            {
                                "$ref": "#/definitions/Spacer"
                            },
                            {
                                "$ref": "#/definitions/ControlGroup"
                            }
                        ]
                    }
                }
            },
            "required": [
                "controls",
                "section"
            ],
            "title": "Osc"
        },
        "OscMessage": {
            "type": "array",
            "maxItems": 2,
            "minItems": 2,
            "items": {
                "items": [
                    {
                        "name": "address",
                        "type": "string"
                    },
                    {
                        "name": "value",
                        "type": "number"
                    }
                ]
            }
        },
        "OscMessageWithLabel": {
            "type": "array",
            "maxItems": 2,
            "minItems": 2,
            "items": [
                {
                    "name": "label",
                    "type": "string"
                },
                {
                    "name": "address",
                    "type": "string"
                },
                {
                    "name": "value",
                    "type": "number"
                }
            ]
        },
        "ControlGroup": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "controls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ControlGroupControl"
                    }
                }
            },
            "required": [
                "name",
                "controls"
            ],
            "title": "ControlGroup"
        },
        "ControlGroupControl": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "$ref": "#/definitions/OscMessage"
                },
                "controls": {
                    "type": "array",
                    "contains": {
                        "oneOf": [
                            {
                                "$ref": "#/definitions/ControlGroupControl"
                            },
                            {
                                "$ref": "#/definitions/Parameter"
                            },
                            {
                                "$ref": "#/definitions/MacroParameter"
                            },
                            {
                                "$ref": "#/definitions/OscMessageWithLabel"
                            }
                        ]
                    }
                }
            },
            "required": [
                "name",
                "controls"
            ],
            "title": "ControlGroupControl"
        }
    }
}

=== KingaJanicka/push2-groovebox/device_definitions/filterb.json
{
    "device_name" : "Filter B",
    "device_slots" : [3],
    "init" : [],
    "osc": {
        "section": "Filter B",
        "controls": [
            ["A", "/param/a/feg/attack", 0.0, 1.0],
            ["D", "/param/a/feg/decay", 0.0, 1.0],
            ["S", "/param/a/feg/sustain", 0.0, 1.0],
            ["R", "/param/a/feg/release", 0.0, 1.0],
            ["Feedb.", "/param/a/filter/feedback", 0.0, 1.0],
            ["Shaper", "/param/a/waveshaper/drive", 0.0, 1.0],
            ["HP", "/param/a/highpass", 0.0, 1.0],
            ["Filt Bal", "/param/a/filter/balance", 0.0, 1.0],
            ["Shape A", "/param/a/feg/attack_shape", 0.0, 2.0],
            ["Shape D", "/param/a/feg/decay_shape", 0.0, 2.0],
            ["Eg Mode", "/param/a/feg/mode", 0.0, 1.0],
            ["Shape R", "/param/a/feg/release_shape", 0.0, 2.0],
            [],
            {
				"name": "Sh. Cat",
				"controls": [
					{
						"name": "Off",
						"controls": [
							["Off", "/param/a/waveshaper/type", 0.0]
						]
					},
                    {
						"name": "Saturator",
						"controls": [
							["Soft", "/param/a/waveshaper/type", 1.0],
                            ["Med", "/param/a/waveshaper/type", 40.0],
                            ["Hard", "/param/a/waveshaper/type", 2.0],
                            ["Asymm.", "/param/a/waveshaper/type", 3.0],
                            ["OJD", "/param/a/waveshaper/type", 41.0]
						]
					},
                    {
						"name": "Effect",
						"controls": [
							["Sine", "/param/a/waveshaper/type", 4.0],
                            ["Digital", "/param/a/waveshaper/type", 5.0]
						]
					},
                    {
						"name": "Harm",
						"controls": [
							["Harm 2", "/param/a/waveshaper/type", 6.0],
                            ["Harm 3", "/param/a/waveshaper/type", 7.0],
                            ["Harm 4", "/param/a/waveshaper/type", 8.0],
                            ["Harm 5", "/param/a/waveshaper/type", 9.0],
                            ["Add 12", "/param/a/waveshaper/type", 17.0],
                            ["Add 13", "/param/a/waveshaper/type", 18.0],
                            ["Add 14", "/param/a/waveshaper/type", 19.0],
                            ["Add 15", "/param/a/waveshaper/type", 20.0],
                            ["Add 1-5", "/param/a/waveshaper/type", 21.0],
                            ["Add Saw3", "/param/a/waveshaper/type", 22.0],
                            ["Add Sq3", "/param/a/waveshaper/type", 23.0],
                            ["Full Rect", "/param/a/waveshaper/type", 10.0]
						]
					},
                    {
						"name": "Rectifier",
						"controls": [
                            ["Full Rect", "/param/a/waveshaper/type", 10.0],
                            ["Half Pos", "/param/a/waveshaper/type", 11.0],
                            ["Half Neg", "/param/a/waveshaper/type", 12.0],
                            ["Soft Rect", "/param/a/waveshaper/type", 13.0]
						]
					},
                    {
						"name": "Wavefolders",
						"controls": [
                            ["Soft Single", "/param/a/waveshaper/type", 42.0],
                            ["One", "/param/a/waveshaper/type", 14.0],
                            ["Two", "/param/a/waveshaper/type", 15.0],
                            ["West Coast", "/param/a/waveshaper/type", 16.0]
						]
					},
                    {
						"name": "Fuzz",
						"controls": [
                            ["Fuzz", "/param/a/waveshaper/type", 24.0],
                            ["Heavy", "/param/a/waveshaper/type", 26.0],
                            ["Center", "/param/a/waveshaper/type", 27.0],
                            ["Soft", "/param/a/waveshaper/type", 25.0],
                            ["Edge", "/param/a/waveshaper/type", 228.0]
						]
					},
                    {
						"name": "Trig",
						"controls": [
                            ["Sin+x", "/param/a/waveshaper/type", 29.0],
                            ["Sin 2x+x", "/param/a/waveshaper/type", 30.0],
                            ["Sin 3x+x", "/param/a/waveshaper/type", 31.0],
                            ["Sin 7x+x", "/param/a/waveshaper/type", 32.0],
                            ["Sin 10x+x", "/param/a/waveshaper/type", 33.0],
                            ["2 Cycle", "/param/a/waveshaper/type", 34.0],
                            ["7 Cycle", "/param/a/waveshaper/type", 35.0],
                            ["10 Cycle", "/param/a/waveshaper/type", 36.0],
                            ["2 Bound", "/param/a/waveshaper/type", 37.0],
                            ["7 Bound", "/param/a/waveshaper/type", 38.0],
                            ["10 Bound", "/param/a/waveshaper/type", 39.0]
						]
					}
				]
			},
            []
          ]
      }

}
