=== KingaJanicka/push2-groovebox/device_definitions/schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Device",
    "definitions": {
        "Device": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "device_name": {
                    "type": "string"
                },
                "device_slots": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "minItems": 1,
                        "maxItems": 8
                    }
                },
                "init": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Parameter"
                    }
                },
                "osc": {
                    "$ref": "#/definitions/Osc"
                }
            },
            "required": [
                "device_name",
                "device_slots",
                "init",
                "osc"
            ],
            "title": "Device"
        },
        "Parameter": {
            "type": "array",
            "title": "Parameter",
            "minItems": 2,
            "maxItems": 4,
            "prefixItems": [
                {
                    "type": "string"
                },
                {
                    "type": "string"
                },
                {
                    "type": "number"
                },
                {
                    "type": "number"
                }
            ]
        },
        "Osc": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "section": {
                    "type": "string"
                },
                "controls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OscControl"
                    }
                }
            },
            "required": [
                "controls",
                "section"
            ],
            "title": "Osc"
        },
        "ControlGroup": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "pages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Page"
                    }
                }
            },
            "required": [
                "name",
                "pages"
            ],
            "title": "ControlGroup"
        },
        "Page": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "controls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Parameter"
                    }
                }
            },
            "required": [
                "controls",
                "name"
            ],
            "title": "Page"
        },
        "OscControl": {
            "anyOf": [
                {
                    "$ref": "#/definitions/Parameter"
                },
                {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Parameter"
                    }
                },
                {
                    "$ref": "#/definitions/Spacer"
                },
                {
                    "$ref": "#/definitions/ControlGroup"
                }
            ],
            "title": "OscControl"
        },
        "Spacer": {
            "type": "array",
            "maxItems": 0
        }
    }
}

=== KingaJanicka/push2-groovebox/device_definitions/fm2_2.json
{
    "device_name" : "FM2",
    "device_slots" : [1],
    "init" : [["unmute osc", "/param/a/mixer/osc2/mute", 0.0 ], ["set osc type", "/param/a/osc/2/type", 6.0 ]],
    "osc": {
        "section": "FM2",
        "controls": [
            ["PITCH", "/param/a/osc/2/pitch", 0.0, 1.0],
            ["M1 AMOUNT", "/param/a/osc/2/param1", 0.0, 1.0],
            ["M1 RATIO", "/param/a/osc/2/param2", 0.0, 32.0],
            ["M2 AMOUNT", "/param/a/osc/2/param3", 0.0, 1.0],
            ["M2 RATIO", "/param/a/osc/2/param4", 0.0 , 32.0],
            ["M1/2 OFFSET", "/param/a/osc/2/param5", 0.0 , 1.0],
            ["M1/2 PHASE", "/param/a/osc/2/param6", 0.0, 1.0],
            ["FEEDBACK", "/param/a/osc/2/param7", 0.0, 1.0],
            [],
            [],
            ["KEYTRACK", "/param/a/osc/2/keytrack", 0.0, 1.0],
            ["RETRIG", "/param/a/osc/2/retrigger", 0.0, 1.0],
            ["FIL ROUTE", "/param/a/mixer/osc2/route", 0.0 , 2.0],
            [],
            ["FM DEPTH", "/param/a/osc/fm_depth", 0.0, 1.0],
            ["FM ROUTING", "/param/a/osc/fm_routing", 0.0, 3.0]
          ]
      }

}
